In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
arr1 = np.array([3,5,6,7,4,1,1])

In [4]:
arr1

array([3, 5, 6, 7, 4, 1, 1])

# single dimension array using arrange

In [6]:
arr2 = np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])

# initization numpy array with zeros

In [9]:
arr3 = np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# initization  an array matrix with full

In [10]:
arr4 = np.full((4,5),5)
arr4

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

# Multidimension array 

In [12]:
arr5 = np.array([[1,2,5,8],
                 [4,8,9,7],
                 [5,9,8,7]])
arr5

array([[1, 2, 5, 8],
       [4, 8, 9, 7],
       [5, 9, 8, 7]])

# initilization numpy  array with the random number

In [3]:
arr6 = np.random.randint(1,1514,12)
arr6

array([ 230, 1437,  260,    9,  166, 1234,  354, 1460,  974, 1147, 1210,
        667])

In [4]:
arr6.shape 

(12,)

# Reshaping 

In [21]:
arr6.shape = (4,3) 

array([[ 352,  635,  435],
       [ 689,  634,  375],
       [1103,  150,  880],
       [ 771,  719, 1511]])

# The three way of stacking of numpy array 

In [22]:
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,10)
c = np.random.randint(1,100,10)
d = np.random.randint(1,100,10)
e = np.random.randint(1,100,10)
a,b,c,d,e

(array([36, 40, 27, 24, 32, 70, 49,  6, 15, 35]),
 array([ 2, 18, 81, 73, 84, 61, 45, 82, 90, 52]),
 array([88, 25, 72, 80, 39, 26, 81, 62,  7, 16]),
 array([13,  6,  7, 45, 45, 25, 43, 20, 85, 97]),
 array([ 2, 51, 74, 28,  2, 19, 47, 82, 75, 87]))

In [24]:
np.vstack((a,b,c,d,e)) # joining the numpy using vstack

array([[36, 40, 27, 24, 32, 70, 49,  6, 15, 35],
       [ 2, 18, 81, 73, 84, 61, 45, 82, 90, 52],
       [88, 25, 72, 80, 39, 26, 81, 62,  7, 16],
       [13,  6,  7, 45, 45, 25, 43, 20, 85, 97],
       [ 2, 51, 74, 28,  2, 19, 47, 82, 75, 87]])

In [25]:
np.hstack((a,b,c,d,e)) # joing the numpy usoing hstack

array([36, 40, 27, 24, 32, 70, 49,  6, 15, 35,  2, 18, 81, 73, 84, 61, 45,
       82, 90, 52, 88, 25, 72, 80, 39, 26, 81, 62,  7, 16, 13,  6,  7, 45,
       45, 25, 43, 20, 85, 97,  2, 51, 74, 28,  2, 19, 47, 82, 75, 87])

In [27]:
np.column_stack((a,b,c,d,e))  # join the numpy using columns_stack

array([[36,  2, 88, 13,  2],
       [40, 18, 25,  6, 51],
       [27, 81, 72,  7, 74],
       [24, 73, 80, 45, 28],
       [32, 84, 39, 45,  2],
       [70, 61, 26, 25, 19],
       [49, 45, 81, 43, 47],
       [ 6, 82, 62, 20, 82],
       [15, 90,  7, 85, 75],
       [35, 52, 16, 97, 87]])

# numpy intersection and differencence

In [37]:
x = np.array([1,3,5,7,9,4,6,4,8])
y = np.array([2,4,6,9,7,6,4,7,8])

In [31]:
np.intersect1d(x,y)

array([4, 6, 7, 9])

In [32]:
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.setxor1d(x,y)  # union -  intersection  symmatric diff

array([1, 2, 3, 5, 8])

# Addition on numpy

In [38]:
np.sum([x,y])

100

In [39]:
np.sum([x,y],axis=0) # for row

array([ 3,  7, 11, 16, 16, 10, 10, 11, 16])

In [42]:
np.sum([x,y],axis = 1) # for columns

array([47, 53])

In [50]:
np.subtract(x,y)  

array([-1, -1, -1, -2,  2, -2,  2, -3,  0])

# numpy  array mathematics

In [51]:
np.pi

3.141592653589793

In [52]:
p = np.array([10,20,30])

In [53]:
p+1

array([11, 21, 31])

In [54]:
p*5

array([ 50, 100, 150])

In [55]:
p/2

array([ 5., 10., 15.])

In [56]:
p//2

array([ 5, 10, 15], dtype=int32)

# Numpy math functions

In [69]:
ar = np.random.randint(1,100,20)
ar

array([38, 68, 14, 75, 31,  9, 48, 62, 36, 69, 84, 83, 50, 81, 75, 35, 80,
       38, 42, 15])

In [70]:
np.mean(ar)

51.65

In [71]:
np.median(ar)

49.0

In [72]:
np.std(ar)

23.948434186810626

In [73]:
np.var(ar)

573.5274999999999

In [74]:
np.cov(ar)

array(603.71315789)

In [76]:
np.quantile(ar,[0.50])

array([49.])

In [78]:
np.power(5,4)

625

In [110]:
x = np.array([1,3,5,7,9,4,6,4,8])
y = np.array([2,4,6,9,7,6,4,7,8])

In [79]:
np.power(x,y)

array([       1,       81,    15625, 40353607,  4782969,     4096,
           1296,    16384, 16777216])

In [80]:
np.mod(x,y)

array([1, 3, 5, 7, 2, 4, 2, 4, 0])

In [111]:
np.remainder(x,y)

array([1, 3, 5, 7, 2, 4, 2, 4, 0])

In [83]:
z = np.square(x)
z

array([ 1,  9, 25, 49, 81, 16, 36, 16, 64])

In [84]:
np.sqrt(z)

array([1., 3., 5., 7., 9., 4., 6., 4., 8.])

In [113]:
d = np.rad2deg(x)
d

array([ 57.29577951, 171.88733854, 286.47889757, 401.07045659,
       515.66201562, 229.18311805, 343.77467708, 229.18311805,
       458.3662361 ])

In [114]:
np.deg2rad(d)

array([1., 3., 5., 7., 9., 4., 6., 4., 8.])

In [115]:
np.ceil(d)

array([ 58., 172., 287., 402., 516., 230., 344., 230., 459.])

In [116]:
np.floor(d)

array([ 57., 171., 286., 401., 515., 229., 343., 229., 458.])

In [121]:
np.clip(d,20,300)

array([ 57.29577951, 171.88733854, 286.47889757, 300.        ,
       300.        , 229.18311805, 300.        , 229.18311805,
       300.        ])

In [122]:
np.trunc(d)

array([ 57., 171., 286., 401., 515., 229., 343., 229., 458.])

In [124]:
np.fix(d)

array([ 57., 171., 286., 401., 515., 229., 343., 229., 458.])

In [123]:
np.round(d, decimals=3)

array([ 57.296, 171.887, 286.479, 401.07 , 515.662, 229.183, 343.775,
       229.183, 458.366])

In [125]:
np.prod(d)

4.82943939255331e+21

In [126]:
np.cumsum(d)

array([  57.29577951,  229.18311805,  515.66201562,  916.73247221,
       1432.39448783, 1661.57760588, 2005.35228296, 2234.53540101,
       2692.90163711])

In [127]:
np.reciprocal(d)

array([0.01745329, 0.00581776, 0.00349066, 0.00249333, 0.00193925,
       0.00436332, 0.00290888, 0.00436332, 0.00218166])

In [ ]:
x = np.array([1,3,5,7,9,4,6,4,8])
y = np.array([2,4,6,9,7,6,4,7,8])

In [129]:
np.gcd(x,y)

array([1, 1, 1, 1, 1, 2, 2, 1, 8])

In [130]:
np.lcm(x,y)

array([ 2, 12, 30, 63, 63, 12, 12, 28,  8])

# Trignometric Function

In [85]:
arr = np.array([0.5,1.0,1.5,2])

In [86]:
np.sin(arr)

array([0.47942554, 0.84147098, 0.99749499, 0.90929743])

In [87]:
np.tan(arr)

array([ 0.54630249,  1.55740772, 14.10141995, -2.18503986])

In [88]:
np.cos(arr)

array([ 0.87758256,  0.54030231,  0.0707372 , -0.41614684])

In [92]:
np.arcsin(arr)

array([0.52359878, 1.57079633,        nan,        nan])

In [93]:
np.arccos(arr)

array([1.04719755, 0.        ,        nan,        nan])

In [94]:
np.tanh(arr)

array([0.46211716, 0.76159416, 0.90514825, 0.96402758])

In [95]:
np.exp(arr)

array([1.64872127, 2.71828183, 4.48168907, 7.3890561 ])

In [101]:
np.exp2(arr)

array([1.41421356, 2.        , 2.82842712, 4.        ])

In [106]:
y = np.log1p(arr)  # it working with adding 1

In [107]:
np.expm1(y)  # e^(x)-1

array([0.5, 1. , 1.5, 2. ])

# Saving and loading numpy array

In [131]:
n11 = np.array([2,5,6,8,9,6,5])
np.save('my_name', n11)

In [132]:
np.load('my_name.npy')

array([2, 5, 6, 8, 9, 6, 5])

In [134]:
import os
os.makedirs("Sudip", exist_ok = True)

In [136]:
os.getcwd()
os.listdir()

['.ipynb_checkpoints',
 '.virtual_documents',
 '01_numPy.ipynb',
 'anaconda_projects',
 'my_name.npy',
 'Sudip']

# create a numpy array for following data from 10 to 1000 andcalculate covarience and compare the value and result generated from scratch and numpy

In [5]:
x = np.random.randint(10,1000,20)
y = np.random.randint(10,1000,20)

In [6]:
x

array([519, 975, 866, 500, 904, 364, 537, 790, 466, 390, 989, 617, 302,
       759,  71, 702, 172, 472, 144, 263])

In [7]:
y

array([286, 666, 383, 988, 774, 409, 480, 643, 679, 193, 392,  23, 750,
       728, 319, 330, 255, 538, 326, 181])

## Calculating Covarience from scratch

In [24]:
sum_x = 0
sum_y = 0
cov = 0
sum_cov = 0
n = len(x)
for i in range(n):
    sum_x += x[i]
    sum_y += x[i]
mean_x = sum_x/n
mean_y = sum_y/n

for i in range(n):
    sum_cov += (x[i] - mean_x)*(y[i] - mean_y)
cov = sum_cov/(n)
cov
    

20543.835000000003

### Calculating covarience using numpy

In [19]:
cov_np = np.cov(x,y)[0,1]
cov_np

21625.089473684206

In [22]:
print(f"Covarience with manually: {cov}")
print(f"Covarience with numpy: {cov_np}")
print(f"the diff on manually and using numpy is {abs(cov-cov_np)}")

Covarience with manually: 20543.835000000003
Covarience with numpy: 21625.089473684206
the diff on manually and using numpy is 1081.2544736842028


#### The difference occurs because the manual calculation divides by n (population covariance), while NumPy by default divides by (n-1), which calculates the sample covariance.