In [33]:
import numpy as np
import math

In [46]:
a = np.array([[2, 3, 1],
              [4, 1, 5],
              [6, 2, 3]])

b = np.array([[1, 4, 2],
              [3, 2, 6],
              [5, 1, 3]])
c = np.array([[3, 1, 4],
              [2, 5, 1],
              [6, 3, 2]])
ai = (np.linalg.inv(a))
bi = (np.linalg.inv(b))
ci = (np.linalg.inv(c))
at = (np.einsum('ij->ji',a))
bt = (np.einsum('ij->ji',b))
ct = (np.einsum('ij->ji',c))
ta = np.einsum('ii',a)
tb = np.einsum('ii',b)
tc = np.einsum('ii',c)

In [23]:
result1 = np.einsum('ij, jk -> ik', at,b)

In [24]:
result1

array([[44, 22, 46],
       [16, 16, 18],
       [31, 17, 41]])

In [25]:
result2 = (np.einsum('ij, jk -> ik',bi, ct)) + (np.einsum('ij, jk ->ik', at, c))

In [26]:
result2

array([[51.        , 39.57142857, 24.14285714],
       [23.8       , 14.1       , 18.5       ],
       [30.4       , 36.01428571, 14.92857143]])

In [30]:
result3 = ((np.einsum('ij, jk -> ik', a, ct)) - (np.einsum('ij, jk->ik', (np.einsum('ij, ij -> ij', at,b)),ci)))

In [31]:
result3

array([[ 9.68493151, 15.83561644, 25.71232877],
       [29.97260274, 18.24657534, 36.93150685],
       [29.65753425, 24.08219178, 48.64383562]])

In [35]:
result4 = (np.pi * a) - np.linalg.det(c)*bt

In [36]:
result4

array([[ 79.28318531, 228.42477796, 368.14159265],
       [304.56637061, 149.14159265,  88.70796327],
       [164.84955592, 444.28318531, 228.42477796]])

In [44]:
result5 = (a + bt)@(c-at)

In [45]:
result5

array([[ 27,   3, -18],
       [ 35, -24, -25],
       [ 30,  -4, -30]])

In [42]:
result6 = (bi*ct + (at@c)*b)

In [43]:
result6

array([[ 50.        , 159.71428571,  49.71428571],
       [ 69.3       ,  27.5       , 102.        ],
       [154.6       ,  35.27142857,  44.71428571]])

In [47]:
result7 = (np.linalg.inv(a+c) @ bt - at @bi) - ((b*ct)@ai + 5*ta*c)

In [48]:
result7

array([[ -94.29047619,  -33.82380952, -116.4047619 ],
       [ -62.40952381, -156.84761905,  -30.02380952],
       [-180.05714286,  -87.79047619,  -60.92857143]])

In [51]:
result8 = np.linalg.det(a)*(bt@c) - 3*np.linalg.inv(b+c)@at + np.pi**2*(at +bt + ct)@(2*a - 3*b + c)

In [52]:
result8

array([[2467.26899191, 1765.42696241,  -74.51279653],
       [1494.65927749,  644.59872035,  240.64008269],
       [2143.988015  , 1801.15977294,  -82.17027157]])

In [53]:
result9 = 7*(a@b@c) - np.pi**3 * bt @ ai @ ct + np.linalg.det(b)*np.linalg.inv(a+c) @(at -ct)

In [54]:
result9

array([[1536.04492904,  958.49157726,  609.05583248],
       [2286.45347487, 1276.47858159, 1341.17762394],
       [2140.40226915, 1997.38343911, 1014.48056615]])

In [55]:
result10 = 4*tc*(a@b - b@c) + np.linalg.inv(at + bt) @ (2*c - np.pi*a)

In [56]:
result10

array([[-281.25063735, -478.60893205,  517.68917824],
       [-680.6947651 , -319.73965051,  119.31442183],
       [-319.24253796,  478.77996107,  241.50817453]])

In [57]:
result11 = -6 * np.linalg.det(a+b)*ct + (a*b*c)@ np.linalg.inv(a+b+c)

In [58]:
result11

array([[ -8493.97235023,  -5664.42396313, -16992.13824885],
       [ -2835.06912442, -14155.94009217,  -8495.65437788],
       [-11332.89400922,  -2837.95852535,  -5648.52995392]])

In [59]:
result12 = 9*np.pi*(bt@at@ct) - np.einsum('ii', a+b+c) * np.linalg.inv(b)@(a-c)

In [60]:
result12

array([[5321.86048416, 6185.79340594, 6961.77184933],
       [5439.6721054 , 4954.28276329, 6277.22778799],
       [6658.59993908, 6471.69098231, 8539.7803092 ]])

In [61]:
result = result1 + result2 - result3 + result4 + result5 - result6 + result7 + result8 + result9 + result10 - result11 + result12

In [62]:
result

array([[17585.20389561, 14179.14947155, 25234.59538578],
       [11592.84346115, 20664.20790515, 16405.26694123],
       [21848.57657331, 13933.12605525, 15462.19538886]])