In [35]:
import numpy as np
import math

In [5]:
a = np.array([10,45,78,23,40,99,78,56,90,34,44,66,77,88,98,9,3])
bins = np.array([0,10,20,30,40,50,60,70,90])
np.digitize(a,bins)

# -<= x > = 0
# 0<= x > 10 = 1
# 10<= x > 20 = 2
# 20<= x > 30 = 3
# 30<= x > 40 = 4
# 40<= x > 50 = 5
# 50<= x > 60 = 6
# 60<= x > 70 = 7
# 70<= x > 90= 8
# 90<= x = 9

array([2, 5, 8, 3, 5, 9, 8, 6, 9, 4, 5, 7, 8, 8, 9, 1, 1], dtype=int64)

In [6]:
b = np.array([-75, -0.58, -0.38, 1.0, 2.8, 5.6, 6.9])
bins = np.array([-50, -30, -10, 0, 4, 5])
np.digitize(b, bins)

array([0, 3, 3, 4, 4, 6, 6], dtype=int64)

### np.count_nonzero(a)

In [9]:
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

### np.sort

In [12]:
arr = ([3,5,7,3,22,5,7,8])
# np.sort(arr)[::-1]  for desc order
np.sort(arr)

array([ 3,  3,  5,  5,  7,  7,  8, 22])

### np.abs

In [13]:
A = ([[3,-6,7],[4,-9,-2]])
np.abs(A)     

array([[3, 6, 7],
       [4, 9, 2]])

### clip
#### it is used to keep the value of an array with in range

In [15]:
arr = np.array([4,6,7,8,-4,-9,99,7])
# arr.clip(-5,10)  ---> ([ 4,  6,  7,  8, -4, -5, 10,  7])
arr.clip(0,7)

array([4, 6, 7, 7, 0, 0, 7, 7])

In [20]:
A = np.array([[7,6,-5,4,3,2],
      [7,6,5,4,-3,2]])
B = np.array([[2,6],
      [7,-9],
      [-8,10],
      [11,15],
      [0,9],
      [6,7]])

In [36]:
eig_values, eig_vectors = np.linalg.eig(A @ B)
result = ((np.abs(A).T) * np.abs(B)) 

In [37]:
result.flatten()

array([14, 42, 42, 54, 40, 50, 44, 60,  0, 27, 12, 14])

Find the SVD of given matrix $$
A =
\begin{bmatrix}
1 & 2 & 7 & 9 \\
8 & 10 & 12 & 5 \\
6 & 8 & 9 & 10
\end{bmatrix}
$$

In [4]:
A = np.array([[1, 2, 7, 9],
              [8,10,12,5],
              [6, 8, 9,10]])

In [39]:
AT = np.einsum('ij->ji', A)
ATA = np.einsum('ij,jk -> ik', AT, A)
eigenvalues, V = np.linalg.eig(ATA)
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
V = V[:, idx]
singular_values = np.sqrt(eigenvalues)
Sigma = np.zeros((3,4))

for i in range(3):
    Sigma[i,i] = singular_values[i]

U = np.zeros((3,3))

for i in range(3):
    Av = np.einsum('ij,j->i', A, V[:,i])
    U[:,i] = Av / singular_values[i]
    VT = np.einsum('ij->ji', V)

US = np.einsum('ij,jk->ik', U, Sigma)
A_reconstructed = np.einsum('ij,jk->ik', US, VT)

print("Reconstructed A =\n", A_reconstructed)

Reconstructed A =
 [[ 1.  2.  7.  9.]
 [ 8. 10. 12.  5.]
 [ 6.  8.  9. 10.]]


C:\Users\Asus\AppData\Local\Temp\ipykernel_24044\2739342853.py:7: RuntimeWarning: invalid value encountered in sqrt
  singular_values = np.sqrt(eigenvalues)


In [40]:
Sigma = np.zeros((3,4))

for i in range(3):
    Sigma[i,i] = singular_values[i]

print("Sigma =\n", Sigma)

Sigma =
 [[26.31523851  0.          0.          0.        ]
 [ 0.          7.17094796  0.          0.        ]
 [ 0.          0.          2.25515576  0.        ]]
