$$
A =
\begin{bmatrix}
3 & 1 \\
1 & 3 \\
\end{bmatrix}
$$

In [1]:
import numpy as np

In [3]:
A = np.array([[3, 1],
              [1, 3]])

In [6]:
AtA = A.T @ A
AtA

array([[10,  6],
       [ 6, 10]])

In [7]:
eigenvalue, eigenvector = np.linalg.eig(AtA)
eigenvalue, eigenvector

(array([16.,  4.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [12]:
singular_values = np.sqrt(np.sort(eigenvalue)[::-1])
singular_value = np.diag(singular_values)

In [13]:
singular_value

array([[4., 0.],
       [0., 2.]])

In [26]:
U = (A @ eigenvector[:,0])/singular_values[:1]


In [27]:
U

array([0.70710678, 0.70710678])

In [14]:
U,sigma,vt =np.linalg.svd(A) 

In [15]:
U

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [16]:
sigma

array([4., 2.])

In [17]:
vt

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])